const Homeproduct = [
    {
        id: 1,
        name: "SRH Helmet Motorsports Helmet  (Grey, Black)",
        price: 380,
        type: "new",
        category: "Accessories",
        image: "images/products/1.jpg",
        details: "The SRH Helmet Motorsports Helmet in a sleek Grey and Black color combination is designed for riders who prioritize both safety and style. Built with a sturdy outer shell, this helmet offers reliable protection during high-speed rides and daily commutes. Its aerodynamic design reduces wind resistance, while the snug interior padding ensures a comfortable and secure fit for extended wear. The helmet features a clear visor for enhanced visibility and protection from dust, debris, and harsh weather conditions. Whether you're into motorsports or regular biking, the SRH Helmet provides the perfect blend of performance, comfort, and modern aesthetics, making it a dependable companion on every ride.",

    },
    {
        id: 2,
        name: "WZATCO Yuva Go Android 13.0 Smart Projector, 1080P & 4K Support, Rotatable Design, Auto & 4D Keystone with Netflix, Prime etc, WiFi 6 & BT, Screen Mirroring, ARC, 720P Native, White",
        price: 6589,
        type: "featured",
        category: "Electronics",
        image: "images/products/2.jpg",
        details: "The WZATCO Yuva Go Android 13.0 Smart Projector is a compact yet powerful home entertainment solution, designed for modern streaming and versatile projection. Featuring a native 720P resolution with support for Full HD 1080P and even 4K playback, it delivers crisp visuals ideal for movies, shows, and gaming. Running on the latest Android 13.0 OS, the projector comes preloaded with popular apps like Netflix, Amazon Prime Video, and YouTube, allowing you to stream directly without any external device. Its innovative rotatable design makes it easy to project onto walls or ceilings, while auto keystone correction and 4D manual adjustment ensure a perfectly aligned image from any angle. Connectivity is future-ready with Wi-Fi 6 for faster, more stable streaming and Bluetooth 5.0 for wireless pairing with speakers or headphones. The projector also supports screen mirroring from smartphones, tablets, and laptops, making content sharing seamless. With ARC (Audio Return Channel) via HDMI, you can connect to external sound systems for a more immersive audio experience. Despite its advanced features, the Yuva Go remains lightweight and portable, finished in a stylish white design that fits easily into any room or setup. It's the perfect choice for those seeking a smart, flexible, and high-quality projector for home or travel.",
    },
    {
        id: 3,
        name: "Girls Floral Print Flared Kurta Set",
        price: 499,
        type: "top",
        category: "Clothing",
        image: "images/products/3.jpg",
        details: "The Girls Floral Print Flared Kurta Set is a charming and elegant outfit designed to bring comfort and style to any occasion. Featuring a beautifully crafted floral print that adds a touch of vibrance and freshness, this set includes a flared kurta that enhances the overall silhouette, making it perfect for festive gatherings, family functions, or casual wear. Made from soft and breathable fabric, it ensures all-day comfort for active young girls while keeping them stylish. The set is thoughtfully coordinated with matching bottoms, creating a complete and graceful ethnic look. Whether it's a celebration or a special day out, this kurta set is a delightful addition to any girl’s wardrobe, blending traditional appeal with modern design.",
    },
    {
        id: 4,
        name: "Atomberg Zenova Mixer Grinder | Unique Coarse Mode for Silbatta-like Texture | Intelligent BLDC Motor | Safety Features | 4 Jars including Chopper | Hands-Free Operation (Black)",
        price: 6999,
        type: "new",
        category: "Appliances",
        image: "images/products/4.jpg",
        details: "The Atomberg Zenova Mixer Grinder is a state-of-the-art kitchen appliance designed to combine traditional cooking textures with modern technology. Powered by an intelligent BLDC motor, it ensures energy-efficient performance while delivering high torque and consistent grinding results. What sets this mixer grinder apart is its unique Coarse Mode, specially engineered to replicate the silbatta-like texture, ideal for authentic Indian chutneys and masalas. The Zenova offers hands-free operation for convenience, and comes with 4 versatile jars, including a dedicated chopper jar to handle everything from dry grinding to food preparation tasks. Built with advanced safety features, it protects against overheating, voltage fluctuations, and jar misalignment. Sleek and stylish in black, the Atomberg Zenova is perfect for modern kitchens seeking both performance and traditional flavor.",
    },
    {
        id: 5,
        name: "ProV California Independence Almonds  (2 x 250 g)",
        price: 698,
        type: "new",
        category: "Grocery",
        image: "images/products/5.jpg",
        details: "ProV California Independence Almonds (2 x 250 g) bring you premium-quality almonds sourced directly from the fertile orchards of California. Known for their rich flavor, uniform size, and superior crunch, these Independence variety almonds are packed with natural nutrients, including protein, fiber, healthy fats, vitamin E, and antioxidants. Each pack contains 2 sealed 250 g pouches, ensuring freshness and convenience for daily snacking or cooking. Ideal for health-conscious individuals, these almonds make a perfect addition to smoothies, desserts, cereals, or can be enjoyed on their own as a wholesome snack. With no added preservatives or artificial ingredients, ProV California Almonds are a nutritious and delicious choice for your everyday diet.",
    },
    {
        id: 6,
        name: "OPPO K13 5G with 7000mAh and 80W SUPERVOOC Charger In-The-Box (Icy Purple, 256 GB)  (8 GB RAM)",
        price: 19999,
        type: "featured",
        category: "Mobiles",
        image: "images/products/6.jpg",
        details: "The OPPO K13 5G in stunning Icy Purple is a feature-packed smartphone that combines powerful performance with cutting-edge technology. Equipped with a massive 7000mAh battery, it ensures long-lasting usage, easily powering through heavy tasks, streaming, and gaming without frequent recharges. To complement this, the phone includes an 80W SUPERVOOC charger in the box, delivering ultra-fast charging that gets you back to full power in no time. With 8 GB of RAM and a spacious 256 GB of internal storage, the OPPO K13 5G offers smooth multitasking and ample space for all your apps, photos, and videos. Designed for speed and efficiency, it supports 5G connectivity, ensuring faster downloads, seamless streaming, and a responsive online experience. Sleek and stylish, the OPPO K13 is the perfect blend of power, performance, and premium design for today’s dynamic users.",
    },
    {
        id: 7,
        name: "Perfect Homes Julian Engineered Wood 2 Door Wardrobe  (Finish Color - Melamine Wenge, Mirror Included, Knock Down)",
        price: 7999,
        type: "featured",
        category: "Furniture",
        image: "images/products/7.jpg",
        details: "The Perfect Homes Julian Engineered Wood 2 Door Wardrobe is a sleek and functional storage solution designed to elevate the style and organization of your bedroom. Finished in a rich Melamine Wenge color, this wardrobe offers a contemporary look that seamlessly complements modern interiors. Crafted from durable engineered wood, it ensures long-lasting performance while being easy to maintain. The wardrobe features two spacious doors with a thoughtfully designed interior that includes hanging space and shelves for organizing clothes, accessories, and essentials. It also comes with a full-length mirror, adding both convenience and visual appeal. Delivered in a knock-down format, it is easy to transport and assemble, making it ideal for urban homes. Stylish, practical, and space-efficient, the Julian wardrobe is a perfect addition to any home.",
    },
    {
        id: 8,
        name: "EliteAuto Sticker & Decal for Car & Bike  (Black)",
        price: 191,
        type: "new",
        category: "Accessories",
        image: "images/products/8.jpg",
        details: "The EliteAuto Sticker & Decal for Car & Bike (Black) is a stylish and durable accessory designed to enhance the look of your vehicle. Made from high-quality vinyl material, this decal offers excellent adhesion and weather resistance, ensuring it stays intact through various driving conditions. Its sleek black finish adds a bold, eye-catching touch to any car or bike, making it a great choice for those looking to personalize their ride. Easy to apply and remove without leaving residue, the EliteAuto sticker is perfect for both exterior and interior surfaces. Whether you're going for a sporty, minimal, or custom look, this decal adds a unique flair to your vehicle's appearance.",
    },
    {
        id: 9,
        name: "Pigeon Favourite Electric Kettle  (1.5 L, Silver, Black) #JustHere",
        price: 549,
        type: "top",
        category: "Electronics",
        image: "images/products/9.jpg",
        details: "The Pigeon Favourite Electric Kettle (1.5 L, Silver, Black) is a convenient and efficient appliance designed to make your daily routine easier. With a generous 1.5-liter capacity, it's perfect for boiling water quickly for tea, coffee, instant noodles, or soups. Crafted with a durable stainless steel body in a stylish silver and black finish, the kettle combines functionality with modern aesthetics. It features a 360-degree swivel base, automatic shut-off, and boil-dry protection for added safety and ease of use. Lightweight and compact, it’s ideal for both home and office use. Available #JustHere, this electric kettle is a practical addition to any kitchen, offering fast performance and reliable quality from a trusted brand.",
    },
    {
        id: 10,
        name: "PUMA Men Solid Casual Jacket",
        price: 1499,
        type: "new",
        category: "Clothing",
        image: "images/products/10.jpg",
        details: "The PUMA Men Solid Casual Jacket is a versatile and stylish addition to any wardrobe, perfect for everyday wear. Crafted from high-quality materials, this jacket offers a comfortable fit and durability, making it ideal for casual outings or layering during cooler weather. Featuring a sleek solid color design, it combines modern style with sporty aesthetics, reflecting PUMA’s signature look. The jacket is designed with practical details such as a full front zipper, ribbed cuffs, and pockets for convenience. Whether you're heading out for a walk, meeting friends, or just looking to add a sporty edge to your outfit, this PUMA casual jacket delivers both comfort and contemporary style effortlessly.",
    },
    {
        id: 11,
        name: "Greenchef AGNI 2 Steel Gas Lighter  (Silver, Pack of 2)",
        price: 119,
        type: "top",
        category: "Appliances",
        image: "images/products/11.jpg",
        details: "The Greenchef AGNI 2 Steel Gas Lighter (Silver, Pack of 2) is a practical and reliable kitchen accessory designed to make lighting your gas stove quick and effortless. Crafted from durable stainless steel, these lighters feature a sleek silver finish and are built to withstand daily use. The mechanical spark ignition system eliminates the need for batteries or charging, providing consistent performance every time. Each pack includes two lighters, ensuring you have a spare on hand or can use one in multiple cooking areas. With a compact design, they are easy to handle and store, making them a convenient addition to any kitchen setup. Whether you're replacing an old lighter or looking for a reliable backup, the Greenchef AGNI 2 Steel Gas Lighter offers both functionality and value.",
    },
    {
        id: 12,
        name: "Saffola Active Rice Bran & Soyabean refined oil, Less oil absorption for weight watchers Blended Oil Pouch  (4 x 850 g)",
        price: 605,
        type: "new",
        category: "Grocery",
        image: "images/products/12.jpg",
        details: "The Saffola Active Rice Bran & Soyabean Refined Oil (4 x 850 g) is a health-conscious cooking oil blend designed for weight watchers and health enthusiasts. This oil combines 80% refined rice bran oil and 20% refined soyabean oil, leveraging the benefits of both to provide a balanced fat profile rich in Omega-3 fatty acids and oryzanol, known for their heart-health benefits.A standout feature of this oil is its LOSORB™ technology, which reduces oil absorption during cooking by up to 27%, allowing you to enjoy your favorite dishes with less oil, contributing to a healthier diet. Additionally, it is fortified with Vitamins A and D, supporting vision and bone health. The oil's neutral flavor makes it versatile for various cooking methods, including frying, sautéing, and baking.This pack includes four 850 g pouches, offering a total of 3.4 liters of oil, making it an economical choice for families or regular users. The resealable pouches ensure convenience and freshness, and the oil is free from added preservatives and cholesterol.",
    },
    {
        id: 13,
        name: "REDMI A5 (Just Black, 64 GB)  (3 GB RAM)",
        price: 6499,
        type: "featured",
        category: "Mobiles",
        image: "images/products/13.jpg",
        details: "The Redmi A5 (Just Black, 64 GB) is an entry-level smartphone that combines sleek design with practical features, making it an excellent choice for budget-conscious users. Its 6.88-inch HD+ display offers a 120Hz refresh rate and 240Hz touch sampling rate, ensuring smooth visuals and responsiveness. Powered by the Unisoc T7250 octa-core processor, it delivers reliable performance for everyday tasks. The device comes with 3 GB of RAM and 64 GB of internal storage, expandable up to 2 TB via a dedicated microSD card slot, providing ample space for apps, photos, and videos. Equipped with a 32 MP dual rear camera setup and an 8 MP front camera, the Redmi A5 captures clear and vibrant photos. Its 5,200 mAh battery supports 15W fast charging, ensuring long-lasting usage throughout the day. Running on Android 15 Go Edition, the smartphone offers a clean and efficient user interface. With dual SIM support, a side-mounted fingerprint sensor, and IP52 water resistance, the Redmi A5 is a reliable and affordable option for users seeking essential smartphone features. Priced at ₹6,499, it provides excellent value for money in the budget segment.",
    },
    {
        id: 14,
        name: "Bluetooth SpeakerPerfect Homes Opus Engineered Wood Queen Box Bed  (Finish Color - Melamine WoodV Wenge, Delivery Condition - Knock Down)",
        price: 10499,
        type: "featured",
        category: "Furniture",
        image: "images/products/14.jpg",
        details: "The Perfect Homes Opus Engineered Wood Queen Box Bed in Melamine Wenge finish is a stylish and practical addition to any modern bedroom. Crafted from durable particle board, this bed offers a sleek and contemporary look, complemented by a rich Wenge laminate finish that adds warmth to your space. Designed to accommodate a queen-sized mattress (78 X 60), the bed's dimensions are approximately 213 cm (length) x 162.3 cm (width) x 79.9 cm (height). It features a box storage system, providing ample space beneath the bed to store bedding, seasonal items, or other essentials, helping you maintain a clutter-free room. The knock-down delivery condition ensures ease of transport, and professional installation is available to set up the bed in your home. With a weight capacity of up to 250 kg, the Opus bed is built to last, offering both durability and functionality. It's an excellent choice for those seeking a blend of modern design and practical storage solutions in their bedroom furniture.",
    },
    {
        id: 15,
        name: "Portronics Mobike 4 Bike Phone Mount with 360° Rotational, Strong Hold, Navigation Bike Mobile Holder  (Black)",
        price: 298,
        type: "new",
        category: "Accessories",
        image: "images/products/15.jpg",
        details: "The Portronics Mobike 4 Bike Phone Mount is a versatile and reliable accessory designed to securely hold your smartphone on your bicycle or motorcycle handlebar. With a universal fit for devices ranging from 4.7 to 6.8 inches, it accommodates most smartphones, making it suitable for navigation, music control, or hands-free calls while riding. This mount features a 360° rotational design, allowing you to adjust your phone to any angle—portrait or landscape—for optimal viewing. Its one-click locking mechanism ensures a firm grip, preventing your phone from slipping or vibrating during rides. The anti-slip rubber pads provide additional protection, safeguarding your device from scratches and shocks. Installation is straightforward; simply attach the mount to your handlebar using the adjustable clamp, and you're ready to go. Its compact and lightweight design ensures it doesn't add unnecessary bulk to your bike setup.",
    },
    {
        id: 16,
        name: "Dr. Morepen GLUCO ONE BG-03 50 STRIP PACK OF 1 Glucometer  (Black)",
        price: 644,
        type: "featured",
        category: "Electronics",
        image: "images/products/16.jpg",
        details: "The Dr. Morepen GLUCO ONE BG-03 Glucometer is a compact and user-friendly device designed for quick and accurate blood glucose monitoring at home. It delivers results in just 5 seconds using a minimal blood sample of 0.5 µL, making it convenient for regular use. The glucometer measures blood glucose levels in a wide range from 10 mg/dL to 600 mg/dL and can store up to 300 test results, allowing users to track their glucose levels over time. Featuring a large, easy-to-read display and an ergonomic design, it ensures comfort and ease of use. The device comes in a sleek black color and is backed by a lifetime warranty for long-term reliability. Priced affordably, the Dr. Morepen BG-03 is an excellent choice for individuals seeking a reliable, efficient, and easy-to-use glucose monitoring solution.",
    },
    {
        id: 17,
        name: "Girls Printed Cotton Blend Regular T Shirt  (Multicolor, Pack of 3)",
        price: 380,
        type: "new",
        category: "Clothing",
        image: "images/products/17.jpg",
        details: "The Girls Printed Cotton Blend Regular T-Shirt (Multicolor, Pack of 3) is a versatile and stylish addition to any young girl's wardrobe. Crafted from a comfortable cotton blend fabric, these T-shirts offer a soft feel against the skin, making them ideal for daily wear. The pack includes three vibrant colors—typically featuring combinations like yellow, pink, and green—each adorned with playful prints that appeal to young fashion tastes. Designed with a regular fit, these T-shirts provide ample room for movement, ensuring comfort during various activities. The round neck and half sleeves add to the classic design, suitable for casual outings, school wear, or playdates. Easy to maintain, they are machine washable and retain their color and shape even after multiple washes. Available in a range of sizes to fit different age groups, these T-shirts cater to children from 2 to 14 years old. They are offered at an affordable price point, making them an excellent choice for parents seeking quality and style without breaking the bank. Whether you're looking to refresh your child's everyday attire or searching for a thoughtful gift, the Girls Printed Cotton Blend Regular T-Shirt Pack of 3 combines comfort, durability, and fun designs in one convenient package.",
    },
    {
        id: 18,
        name: "Rewop Kitchen Shears Ultra Sharp Utility Plastic Handle, Blade material Stainless Steel All-Purpose Scissor  (Black, Pack of 1)",
        price: 111,
        type: "new",
        category: "Appliances",
        image: "images/products/18.jpg",
        details: "The Rewop Kitchen Shears are a versatile and ultra-sharp utility tool designed for everyday kitchen tasks. Featuring high-quality stainless steel blades, these scissors offer excellent cutting performance and durability, making them suitable for a wide range of uses such as cutting meat, vegetables, herbs, and packaging. The ergonomic plastic handle provides a comfortable and secure grip, ensuring safe and efficient handling. With their all-purpose design and sturdy construction, these black kitchen shears are an essential addition to any kitchen, offering precision and convenience in one handy tool.",
    },
    {
        id: 19,
        name: "Kalbavi Popular W450 Cashews  (1 x 500 g)",
        price: 467,
        type: "top",
        category: "Grocery",
        image: "images/products/19.jpg",
        details: "Kalbavi Popular W450 Cashews come in a convenient 500-gram pack, offering premium quality nuts that are perfect for snacking or cooking. Known for their rich flavor and crunchy texture, these cashews are carefully selected and processed to ensure freshness and taste. Whether enjoyed on their own, added to recipes, or used in desserts, Kalbavi cashews provide a healthy source of nutrients, including protein and healthy fats. Ideal for daily consumption or gifting, this pack delivers both quality and value for cashew lovers.",
    },
    {
        id: 20,
        name: "Nokia 105 Classic with Charger  (Blue) #JustHere",
        price: 989,
        type: "featured",
        category: "Mobiles",
        image: "images/products/20.jpg",
        details: "The Nokia 105 Classic in blue is a reliable and straightforward mobile phone designed for users seeking essential features without any distractions. Known for its durability and long-lasting battery life, this phone comes with a charger included, ensuring you're always powered up. It offers a user-friendly interface, classic design, and basic functionalities like calling, texting, and FM radio, making it an ideal choice for those who want a simple yet efficient device for everyday communication. Compact and lightweight, the Nokia 105 Classic is perfect as a backup phone or for users new to mobile technology.",
    },
    {
        id: 21,
        name: "Perfect Homes Julian Engineered Wood 4 Door Wardrobe  (Finish Color - Almond Walnut, Mirror Included, Knock Down)",
        price: 12999,
        type: "new",
        category: "Furniture",
        image: "images/products/21.jpg",
        details: "The Perfect Homes Julian Engineered Wood 4-Door Wardrobe in Almond Walnut finish is a stylish and durable storage solution designed to enhance any bedroom. Made from high-quality engineered wood, this wardrobe features a warm Almond Walnut color that adds a touch of sophistication to your space. It offers ample storage with four spacious doors opening to reveal 12 shelves, providing plenty of room for clothes and accessories. A built-in mirror adds convenience, making it easy to check your appearance. The wardrobe comes in a knock-down form for easy assembly and is sturdy enough to last long. Combining functionality with modern design, this wardrobe is a practical and elegant addition to your home.",
    },
    {
        id: 22,
        name: "CAR101 Cotton Vehicle Washing Duster  (Pack Of 1)",
        price: 845,
        type: "top",
        category: "Accessories",
        image: "images/products/22.jpg",
        details: "The CAR101 Cotton Vehicle Washing Duster is an effective and gentle cleaning tool designed to keep your vehicle looking spotless. Made from soft, high-quality cotton, this duster safely removes dust, dirt, and grime without scratching the surface of your car or bike. Its absorbent material ensures efficient cleaning, making it ideal for both wet and dry use. Lightweight and easy to handle, the duster provides a convenient solution for regular vehicle maintenance, helping you maintain a polished and shiny finish with minimal effort.",
    },
    {
        id: 23,
        name: "BOMBAY SHAVING COMPANY Flash Charging Men Beard Trimmer 120 min Runtime 38 Length Settings  (Black)",
        price: 849,
        type: "new",
        category: "Electronics",
        image: "images/products/23.jpg",
        details: "The Bombay Shaving Company Flash Charging Men’s Beard Trimmer (Black) is a high-performance grooming tool designed for precision, convenience, and versatility. Equipped with 38 adjustable length settings ranging from 0.5mm to 20mm, it allows users to achieve a variety of beard styles and hair lengths with ease. This trimmer features a USB Type-C port for fast charging, providing a full charge in just 1.5 hours and delivering up to 120 minutes of cordless runtime. The inclusion of two adjustable combs and a smart lock mechanism ensures consistent trimming without accidental setting changes. Its stainless steel blades are designed to be skin-friendly and rust-resistant, offering a smooth and safe grooming experience. With a compact design and lightweight build, the trimmer is easy to handle and suitable for both home and travel use. It comes with a 2-year warranty, ensuring long-term reliability. Priced affordably, it offers excellent value for money. Overall, the Bombay Shaving Company Flash Charging Men’s Beard Trimmer combines advanced features, user-friendly design, and durability, making it a top choice for individuals seeking a reliable and efficient grooming tool.",
    },
    {
        id: 24,
        name: "Solid Women Raincoat",
        price: 368,
        type: "top",
        category: "Clothing",
        image: "images/products/24.jpg",
        details: "The Solid Women Raincoat is a practical and stylish outerwear option designed to keep you dry and comfortable during rainy weather. Made from waterproof and durable materials, this raincoat provides excellent protection against wind and rain. Its lightweight design ensures ease of movement, while features like a hood and secure closures add extra coverage and convenience. Perfect for daily commutes or outdoor activities, this raincoat combines functionality with a simple, classic look suitable for any wardrobe.",
    },
    {
        id: 25,
        name: "Pigeon by Stovekraft Limited Handy Mini Vegetable & Fruit Chopper  (1 chopper)",
        price: 149,
        type: "featured",
        category: "Appliances",
        image: "images/products/25.jpg",
        details: "The Pigeon by Stovekraft Limited Handy Mini Vegetable & Fruit Chopper is a compact and efficient manual kitchen tool designed to simplify food preparation. Featuring three sharp stainless steel blades housed in a durable polypropylene container, this chopper allows you to chop vegetables and fruits effortlessly with a simple pull of the string mechanism. Its 400 ml capacity makes it ideal for small to medium-sized chopping tasks, such as preparing salads, salsas, or garnishes. The BPA-free plastic construction ensures safety and longevity, while the non-slip base provides stability during use. This chopper is easy to assemble and clean, making it a convenient addition to any kitchen. Whether you're a novice cook or an experienced chef, the Pigeon Handy Mini Chopper offers a practical solution for quick and consistent chopping without the need for electricity.",
    },
    {
        id: 26,
        name: "Manna Black Dates - 800g (400g x 2 Packs) | Select Premium Organic Handpicked Dates | Khajoor | Khajur | Soft Dried Healthy Snack | Soft & Juicy texture | Zero Added Sugar & Preservatives",
        price: 387,
        type: "new",
        category: "Grocery",
        image: "images/products/26.jpg",
        details: "Manna Black Dates come in a convenient pack of two, each weighing 400 grams, totaling 800 grams of premium quality organic dates. These handpicked dates are soft, juicy, and naturally sweet, making them a healthy snack option without any added sugar or preservatives. Known for their rich texture and delightful flavor, Manna Black Dates are packed with essential nutrients such as iron, fiber, and vitamins, promoting overall wellness. Perfect for snacking or adding to recipes, these dates offer a nutritious and delicious way to enjoy a natural energy boost.",
    },
    {
        id: 27,
        name: "Apple iPhone 16 (Teal, 256 GB)",
        price: 79999,
        type: "top",
        category: "Mobiles",
        image: "images/products/27.jpg",
        details: "The Apple iPhone 16 in Teal with 256 GB storage offers a powerful and sleek smartphone experience. Equipped with the latest A18 chip, it delivers fast and efficient performance for all your apps and games. The vibrant Teal finish adds a stylish touch, while the large 256 GB storage ensures ample space for photos, videos, and files. The iPhone 16 features advanced camera capabilities, a stunning display, and up to 22 hours of video playback, making it ideal for both work and entertainment. With support for 25W MagSafe wireless charging and a range of smart features, this model combines cutting-edge technology with elegant design.",
    },
    {
        id: 28,
        name: "Wopno Furniture Pure Sheesham Wooden dining Chair Only|2 Chair For Dining Room / Study Room Solid Wood Dining Chair  (Set of 2, Finish Color - Teak)",
        price: 4874,
        type: "new",
        category: "Furniture",
        image: "images/products/28.jpg",
        details: "The Wopno Furniture Pure Sheesham Wooden Dining Chair set includes two beautifully crafted chairs, perfect for your dining room or study area. Made from solid Sheesham wood, these chairs boast durability and timeless elegance. Finished in a rich teak color, they add warmth and sophistication to any space. Designed for comfort and style, the chairs feature a sturdy build that ensures long-lasting use. Ideal for both everyday dining and work-from-home setups, this set combines functionality with classic wooden charm.",
    },
];

export default Homeproduct;